import { defineConfig, devices } from '@playwright/test'

export default defineConfig({
  testDir: './specs',
  timeout: 35_000,
  expect: { timeout: 10_000 },
  // Retry once in CI to tolerate rare timing flakiness
  retries: process.env.CI ? 1 : 0,
  // Serial execution: tests share server-side note state, running in parallel
  // would cause interference between note create/delete operations.
  workers: 1,
  reporter: [
    ['list'],
    ['html', { outputFolder: 'playwright-report', open: 'never' }],
  ],
  use: {
    baseURL: process.env.APP_URL ?? 'http://localhost:8080',
    headless: true,
    // Accept the self-signed certificate generated by TLS_SELF=1 in Docker.
    ignoreHTTPSErrors: true,
    screenshot: 'only-on-failure',
    // Video capture requires Playwright's own custom-built ffmpeg binary.
    // Since we use system Chromium (PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD=1), that binary
    // is not available; disable video to avoid the crash and rely on screenshots.
    video: 'off',
    viewport: { width: 1280, height: 800 },
    actionTimeout: 10_000,
  },
  projects: [
    {
      name: 'chromium',
      use: {
        ...devices['Desktop Chrome'],
        // Required when running as root inside Docker / Alpine containers.
        // System Chromium on Alpine also needs this flag.
        // executablePath lets us use Alpine's system Chromium instead of Playwright's
        // bundled headless_shell when PLAYWRIGHT_CHROMIUM_EXECUTABLE_PATH is set.
        launchOptions: {
          executablePath: process.env.PLAYWRIGHT_CHROMIUM_EXECUTABLE_PATH,
          args: [
            '--no-sandbox',
            '--disable-setuid-sandbox',
            // The E2E app runs with TLS_SELF=1 (HTTPS + self-signed cert).
            // ignoreHTTPSErrors in the `use` section handles Playwright-level cert
            // validation; these flags silence browser-internal SSL enforcement so
            // Chrome does not abort on the self-signed CA before Playwright sees it.
            '--ignore-certificate-errors',
            '--ignore-ssl-errors',
          ],
        },
      },
    },
  ],
})
